push_url = "https://api.day.app/sTc3n8MBtjjjftx5kYPBHg"

gateway = "OKX"

[instrument_info]
instId = "BTC-USDT"
bars = ["5m", "30m", "1H",]
limit = 300

[strategies]
MAOverlap = [ [ 29, 34, 30, 1,], [ 85, 88, 30, 1,], [ 99, 121, 5, 1,],]
RSICrossover = [ [ 24, 99, 60, 1,], [ 52, 61, 60, 1,], [ 68, 1, 60, 1,], [ 98, 35, 60, 1,], [ 98, 57, 30, 1,],]
